
-- MySQL Script generated by MySQL Workbench
-- Sat Feb 15 17:30:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- ----------------------------------------------------
-- -----------------------------------------------------
-- Schema xacademydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xacademydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xacademydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `xacademydb` ;

-- -----------------------------------------------------
-- Table `xacademydb`.`courses_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`courses_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xacademydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `uuid` VARCHAR(255) NULL DEFAULT NULL,
  `userRole` ENUM('ADMIN', 'TEACHER', 'STUDENT') NOT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `dni` INT NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xacademydb`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `specialty` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `teacher_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `xacademydb`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xacademydb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `quota` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `hours` INT NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modalidad` ENUM('PRESENCIAL', 'VIRTUAL', 'HÍBRIDO') NOT NULL,
  `status` ENUM('PENDIENTE', 'ACTIVO', 'FINALIZADO') NOT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT '1',
  `image_url` VARCHAR(255) NOT NULL,
  `category_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courses_courses_category1_idx` (`category_id` ASC) INVISIBLE,
  INDEX `fk_courses_teacher1_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_courses_courses_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `xacademydb`.`courses_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `xacademydb`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xacademydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `qualification` DECIMAL(5,2) NULL DEFAULT NULL,
  `studentCondition` ENUM('EN_CURSO', 'APROBADO', 'DESAPROBADO') NULL DEFAULT 'EN_CURSO',
  `payment_status` ENUM('PENDIENTE', 'PAGADO', 'ATRASADO') NULL DEFAULT 'PENDIENTE',
  `certificate_id` INT NULL DEFAULT NULL,
  `attendance_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `student_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `xacademydb`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `student_ibfk_2`
    FOREIGN KEY (`course_id`)
    REFERENCES `xacademydb`.`courses` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xacademydb`.`assists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`assists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `attendanceDate` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_id` (`course_id` ASC) VISIBLE,
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `assists_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `xacademydb`.`courses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `assists_ibfk_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `xacademydb`.`student` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xacademydb`.`inscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`inscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NULL DEFAULT NULL,
  `student_id` INT NULL DEFAULT NULL,
  `registrationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `course_id` (`course_id` ASC) VISIBLE,
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `inscriptions_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `xacademydb`.`courses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `inscriptions_ibfk_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `xacademydb`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xacademydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `user_id` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `news_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `xacademydb`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xacademydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xacademydb`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('PENDIENTE', 'PAGADO', 'ATRASADO') NULL DEFAULT 'PENDIENTE',
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `course_id` (`course_id` ASC) VISIBLE,
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `xacademydb`.`courses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `payment_ibfk_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `xacademydb`.`student` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
